### ISSUE TITLE
[BUG] TypeScript compile (tsc) errors with 3.8.2

### ISSUE THREAD

**Issue by cduff** [exceljs/exceljs#1178]
## 🐛 Bug Report

tsc returns errors after upgrade to 3.8.2, where 3.8.1 worked fine.

> node_modules/exceljs/index.d.ts(1319,21): error TS2304: Cannot find name 'HeaderTransformFunction'.
> node_modules/exceljs/index.d.ts(1319,47): error TS2304: Cannot find name 'HeaderArray'.
> node_modules/exceljs/index.d.ts(1341,16): error TS2304: Cannot find name 'QuoteColumns'.
> node_modules/exceljs/index.d.ts(1342,16): error TS2304: Cannot find name 'QuoteColumns'.
> node_modules/exceljs/index.d.ts(1346,13): error TS2304: Cannot find name 'RowTransformFunction'.

Lib version: 3.8.2

**Comment by franleplant** [comment]
I just installed the lib and encountered with this error :)

**Comment by furmanServices** [comment]
The same issue. Version 3.7.0 compiles normally. 3.8.0 - also good; 3.8.2 - fails. Seems an author accidentally removed some part of type definitions

**Comment by franleplant** [comment]
Hi @Siemienik do you know when the next release including this fix will be done? can I do anything to help with that?

**Comment by Siemienik** [comment]
only @guyonroche has permissions to do that, I'm waiting for the new version too
