### ISSUE TITLE
typescript definitions for Worksheet.protect() and Worksheet.unprotect() have no explicit return values

### ISSUE THREAD

**Issue by drjokepu** [exceljs/exceljs#925]
Exceljs 1.15.0 can no longer be used with TypeScript when the [--noImplicitReturns](https://www.typescriptlang.org/docs/handbook/compiler-options.html) compiler option is enabled as the build fails with the following messages:

    node_modules/exceljs/index.d.ts:1154:2 - error TS7010: 'protect', which lacks return-type annotation, implicitly has an 'any' return type.
    node_modules/exceljs/index.d.ts:1155:2 - error TS7010: 'unprotect', which lacks return-type annotation, implicitly has an 'any' return type.

This regression was introduced by commit f6468be ("Additional unit tests").
