### ISSUE TITLE
dateUTC option for writeBuffer causes error "m.utc is not a function"

### ISSUE THREAD

**Issue by rkanagy** [exceljs/exceljs#1523]
Hello,

I am attempting to export data to CSV containing date values.  Out of the box, these date values are saved to the CSV as dates in local time, but I want them to be in UTC time.  So, I am using the dateUTC option and passing the options object to writeBuffer as follows:
`                    dayjs.extend(dayjs_plugin_utc);
                    var options = {
                        dateUTC: true
                    };
                    workbook.csv.writeBuffer(options).then(function(buffer) {
                        saveAs(new Blob([buffer], { type: 'application/octet-stream' }), date + ' - @Model.Project.StudyId' + '.csv');
                    });
`
I am also including the following scripts in my ASP.NET Core MVC View:

`    <script src="https://cdnjs.cloudflare.com/ajax/libs/exceljs/3.3.1/exceljs.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dayjs/1.9.5/dayjs.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dayjs/1.9.5/plugin/utc.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.8/FileSaver.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/7.4.0/polyfill.min.js"></script>
`
When I export the data to CSV, I am getting the following error displayed in the Chrome Developer Tools console:

"Uncaught (in promise) TypeError: m.utc is not a function"

Any ideas on what I need to do to get this to work?

Thanks,
Ron Kanagy

**Comment by rkanagy** [comment]
I was able to resolve my issue by going back to version 1.11.0 of ExcelJS which properly handles the dateFormat and dateUTC options for writeBuffer for CSV files correctly.

**Comment by rkanagy** [comment]
As I stated, I was able to get this to work with version 1.11.0 of ExcelJS, but I would like to get this working with the newer versions of ExcelJS that use the dayjs library instead of moment.  I am writing javascript in a browser and not through something like NodeJS.  I was able to get this working using the latest versions of ExcelJS (4.2.0) and dayjs (1.9.5) and adding the javascript code "dayjs.extend(window.dayjs_plugin_utc)" to a script block.
